name = "changli"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

routes = [

  { pattern = "balckwolf.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "demo.appsflyer.com.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "blog.webex.com.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "bimbel.ruangguru.com.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "investor.fb.com.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "nontontv.vidio.com.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "blog.clova.line.me.balckwolf.dpdns.org", custom_domain = true },
]


account_id = "ea1aab81dc8e22018131832d124a54fc"
workers_dev = true

[[kv_namespaces]]
binding = "YUMI"
id = "8ff1913fa986482d967e0a5c7e2b0791"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "aacac2d2-cac8-442a-9f2c-4e4f807065f5"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/zerokit-769/cf/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/zerokit-769/cf/refs/heads/main/web/sub.html"
